/* The Line of Kings — data compiled from the ESV Global Study Bible charts:
   11-02 (evaluations in 1-2 Kings), 11-03a (kings of Judah), 11-03b (kings
   of Israel), 13-02 (Kings/Chronicles parallels). Dates are approximate;
   where the chart gives split years (931/930) the earlier year is used.
   `co` marks the start of a co-regency with the predecessor. */

const KINGS = [
  { name: "Saul", kingdom: "united", start: 1050, end: 1010, years: "40", eval: "bad",
    note: "Israel's first king; anointed then rejected for disobedience. Died at Mount Gilboa.",
    refs: [["1 Samuel 9–31", "1Sam.9.1"], ["1 Chronicles 10", "1Chr.10.1"]] },
  { name: "David", kingdom: "united", start: 1010, end: 971, years: "40", eval: "good",
    note: "“A man after God's own heart” — the covenant king whose line the rest of the story follows, though his sin with Bathsheba fractured his house.",
    refs: [["2 Samuel 1–24", "2Sam.1.1"], ["1 Chronicles 11–29", "1Chr.11.1"]] },
  { name: "Solomon", kingdom: "united", start: 971, end: 931, years: "40", eval: "mixed",
    note: "Built the temple and reigned in unmatched wisdom and wealth; his foreign wives turned his heart, and the kingdom split at his death.",
    refs: [["1 Kings 1–11", "1Kgs.1.1"], ["2 Chronicles 1–9", "2Chr.1.1"]] },

  /* ---- Judah (south) ---- */
  { name: "Rehoboam", kingdom: "judah", start: 931, end: 915, years: "17", eval: "bad",
    note: "Solomon's son; his harsh answer at Shechem split the kingdom. Egypt's Shishak plundered the temple.",
    refs: [["1 Kings 12:1–24; 14:21–31", "1Kgs.14.21"], ["2 Chronicles 10–12", "2Chr.10.1"]] },
  { name: "Abijam", alt: "Abijah", kingdom: "judah", start: 915, end: 912, years: "3", eval: "bad",
    note: "Walked in his father's sins, “yet for David's sake” the lamp in Jerusalem was not put out.",
    refs: [["1 Kings 15:1–8", "1Kgs.15.1"], ["2 Chronicles 13", "2Chr.13.1"]] },
  { name: "Asa", kingdom: "judah", start: 912, end: 871, years: "41", eval: "good",
    note: "Removed the idols and deposed the queen mother; late in life relied on Syria and jailed the seer who rebuked him.",
    refs: [["1 Kings 15:9–24", "1Kgs.15.9"], ["2 Chronicles 14–16", "2Chr.14.1"]] },
  { name: "Jehoshaphat", kingdom: "judah", start: 871, end: 849, co: 873, years: "25", eval: "good",
    note: "Sent teachers of the law through Judah; his alliance with Ahab's house nearly cost him his life at Ramoth-gilead.",
    refs: [["1 Kings 22:41–50", "1Kgs.22.41"], ["2 Chronicles 17–20", "2Chr.17.1"]] },
  { name: "Jehoram", alt: "Joram", kingdom: "judah", start: 849, end: 842, co: 853, years: "8", eval: "bad",
    note: "Married Ahab's daughter Athaliah and killed his own brothers; died of a foretold disease, “with no one's regret.”",
    refs: [["2 Kings 8:16–24", "2Kgs.8.16"], ["2 Chronicles 21", "2Chr.21.1"]] },
  { name: "Ahaziah", kingdom: "judah", start: 842, end: 841, years: "1", eval: "bad",
    note: "Reigned one year; killed by Jehu in the purge of Ahab's house.",
    refs: [["2 Kings 8:25–29; 9:27–29", "2Kgs.8.25"], ["2 Chronicles 22:1–9", "2Chr.22.1"]] },
  { name: "Athaliah", kingdom: "judah", start: 841, end: 835, years: "6", eval: "bad", queen: true,
    note: "Ahab's daughter; massacred the royal seed and usurped the throne. Only the infant Joash was hidden from her. Executed when Jehoiada crowned him.",
    refs: [["2 Kings 11", "2Kgs.11.1"], ["2 Chronicles 22:10–23:21", "2Chr.22.10"]] },
  { name: "Joash", alt: "Jehoash", kingdom: "judah", start: 835, end: 796, years: "40", eval: "mixed",
    note: "Hidden six years in the temple; repaired it under Jehoiada's guidance — then, after the priest died, murdered Jehoiada's son Zechariah.",
    refs: [["2 Kings 12", "2Kgs.12.1"], ["2 Chronicles 24", "2Chr.24.1"]] },
  { name: "Amaziah", kingdom: "judah", start: 796, end: 767, years: "29", eval: "mixed",
    note: "“Did what was right, yet not with a whole heart” — defeated Edom, then bowed to Edom's gods and was routed by Israel.",
    refs: [["2 Kings 14:1–22", "2Kgs.14.1"], ["2 Chronicles 25", "2Chr.25.1"]] },
  { name: "Uzziah", alt: "Azariah", kingdom: "judah", start: 767, end: 740, co: 791, years: "52", eval: "mixed",
    note: "Long, prosperous reign — until pride led him to burn incense in the temple, and he lived out his days a leper. Isaiah's call came “in the year King Uzziah died.”",
    refs: [["2 Kings 15:1–7", "2Kgs.15.1"], ["2 Chronicles 26", "2Chr.26.1"]] },
  { name: "Jotham", kingdom: "judah", start: 750, end: 735, years: "16", eval: "good",
    note: "Governed while his leprous father lived; “he ordered his ways before the LORD his God.”",
    refs: [["2 Kings 15:32–38", "2Kgs.15.32"], ["2 Chronicles 27", "2Chr.27.1"]] },
  { name: "Ahaz", kingdom: "judah", start: 735, end: 715, years: "16", eval: "bad",
    note: "Burned his son as an offering and shut the temple; bought Assyria's help against Israel and Syria despite Isaiah's warning.",
    refs: [["2 Kings 16", "2Kgs.16.1"], ["2 Chronicles 28", "2Chr.28.1"]] },
  { name: "Hezekiah", kingdom: "judah", start: 715, end: 687, co: 728, years: "29", eval: "good",
    note: "Removed the high places and trusted the LORD against Sennacherib — the angel of the LORD struck the Assyrian camp. Isaiah was his prophet.",
    refs: [["2 Kings 18–20", "2Kgs.18.1"], ["2 Chronicles 29–32", "2Chr.29.1"], ["Isaiah 36–39", "Isa.36.1"]] },
  { name: "Manasseh", kingdom: "judah", start: 687, end: 642, co: 697, years: "55", eval: "bad",
    note: "Judah's longest and darkest reign — altars in the temple courts, his son through the fire. Chronicles records his repentance in Babylonian chains.",
    refs: [["2 Kings 21:1–18", "2Kgs.21.1"], ["2 Chronicles 33:1–20", "2Chr.33.1"]] },
  { name: "Amon", kingdom: "judah", start: 642, end: 640, years: "2", eval: "bad",
    note: "Repeated his father's sins without his father's repentance; killed by his own servants.",
    refs: [["2 Kings 21:19–26", "2Kgs.21.19"], ["2 Chronicles 33:21–25", "2Chr.33.21"]] },
  { name: "Josiah", kingdom: "judah", start: 640, end: 609, years: "31", eval: "good",
    note: "The book of the law found during his temple repairs set off Judah's greatest reformation. Died at Megiddo opposing Pharaoh Neco.",
    refs: [["2 Kings 22:1–23:30", "2Kgs.22.1"], ["2 Chronicles 34–35", "2Chr.34.1"]] },
  { name: "Jehoahaz", kingdom: "judah", start: 609, end: 609, years: "3 months", eval: "bad",
    note: "Reigned three months; deposed by Pharaoh Neco and taken to Egypt.",
    refs: [["2 Kings 23:31–35", "2Kgs.23.31"], ["2 Chronicles 36:1–4", "2Chr.36.1"]] },
  { name: "Jehoiakim", kingdom: "judah", start: 609, end: 598, years: "11", eval: "bad",
    note: "Neco's puppet; burned Jeremiah's scroll column by column. Babylon took the first captives — Daniel among them — in his days.",
    refs: [["2 Kings 23:36–24:7", "2Kgs.23.36"], ["2 Chronicles 36:5–8", "2Chr.36.5"]] },
  { name: "Jehoiachin", alt: "Jeconiah", kingdom: "judah", start: 598, end: 597, years: "3 months", eval: "bad",
    note: "Reigned three months; exiled to Babylon in 597 with Ezekiel and ten thousand others. Released from prison in 562 — the last hopeful note of 2 Kings.",
    refs: [["2 Kings 24:8–17", "2Kgs.24.8"], ["2 Chronicles 36:9–10", "2Chr.36.9"]] },
  { name: "Zedekiah", kingdom: "judah", start: 597, end: 586, years: "11", eval: "bad",
    note: "Babylon's appointee who rebelled against Babylon; watched his sons die, then was blinded and chained. Jerusalem and the temple burned in 586.",
    refs: [["2 Kings 24:18–25:21", "2Kgs.24.18"], ["2 Chronicles 36:11–21", "2Chr.36.11"]] },

  /* ---- Israel (north) — “all did evil in the sight of the LORD” ---- */
  { name: "Jeroboam I", kingdom: "israel", start: 931, end: 911, years: "22", eval: "bad",
    note: "Set up the golden calves at Bethel and Dan so the north would not worship in Jerusalem — “the sin of Jeroboam” that every northern king repeats.",
    refs: [["1 Kings 11:26–40; 12:25–14:20", "1Kgs.12.25"]] },
  { name: "Nadab", kingdom: "israel", start: 911, end: 910, years: "2", eval: "bad",
    note: "Killed by Baasha, ending Jeroboam's dynasty as Ahijah had prophesied.",
    refs: [["1 Kings 15:25–31", "1Kgs.15.25"]] },
  { name: "Baasha", kingdom: "israel", start: 910, end: 887, years: "24", eval: "bad",
    note: "Exterminated Jeroboam's house, then walked in Jeroboam's ways himself.",
    refs: [["1 Kings 15:27–16:7", "1Kgs.15.27"]] },
  { name: "Elah", kingdom: "israel", start: 887, end: 886, years: "2", eval: "bad",
    note: "Assassinated by Zimri while drinking himself drunk.",
    refs: [["1 Kings 16:8–14", "1Kgs.16.8"]] },
  { name: "Zimri", kingdom: "israel", start: 886, end: 886, years: "7 days", eval: "bad",
    note: "Reigned seven days; burned the king's house down over himself when Omri besieged Tirzah.",
    refs: [["1 Kings 16:15–20", "1Kgs.16.15"]] },
  { name: "Omri", kingdom: "israel", start: 886, end: 875, years: "12", eval: "bad",
    note: "Fought off the rival Tibni, bought the hill of Samaria and built Israel's capital there. “Did more evil than all who were before him.”",
    refs: [["1 Kings 16:21–28", "1Kgs.16.21"]] },
  { name: "Ahab", kingdom: "israel", start: 875, end: 853, years: "22", eval: "bad",
    note: "With Jezebel made Baal the state religion. Elijah's fire on Carmel, Naboth's vineyard, and death at Ramoth-gilead all belong to his reign.",
    refs: [["1 Kings 16:29–22:40", "1Kgs.16.29"], ["2 Chronicles 18", "2Chr.18.1"]] },
  { name: "Ahaziah", kingdom: "israel", start: 853, end: 852, years: "2", eval: "bad",
    note: "Fell through a lattice and sent to Baal-zebub instead of the LORD; Elijah pronounced his death.",
    refs: [["1 Kings 22:51–2 Kings 1:18", "1Kgs.22.51"]] },
  { name: "Joram", alt: "Jehoram", kingdom: "israel", start: 852, end: 841, years: "12", eval: "bad",
    note: "Ahab's second son; Elisha's ministry ran through his reign. Shot by Jehu in Naboth's field.",
    refs: [["2 Kings 3", "2Kgs.3.1"], ["2 Kings 9:14–26", "2Kgs.9.14"]] },
  { name: "Jehu", kingdom: "israel", start: 841, end: 814, years: "28", eval: "bad",
    note: "Anointed to destroy Ahab's house — and did, furiously, wiping out Baal worship. Yet he kept Jeroboam's calves, so the verdict still stands against him.",
    refs: [["2 Kings 9–10", "2Kgs.9.1"]] },
  { name: "Jehoahaz", kingdom: "israel", start: 814, end: 798, years: "17", eval: "bad",
    note: "Syria ground Israel down to fifty horsemen in his days.",
    refs: [["2 Kings 13:1–9", "2Kgs.13.1"]] },
  { name: "Jehoash", alt: "Joash", kingdom: "israel", start: 798, end: 782, years: "16", eval: "bad",
    note: "Wept at Elisha's deathbed; recovered towns from Syria and looted Jerusalem after Amaziah picked a fight.",
    refs: [["2 Kings 13:10–25", "2Kgs.13.10"], ["2 Kings 14:8–16", "2Kgs.14.8"]] },
  { name: "Jeroboam II", kingdom: "israel", start: 782, end: 753, co: 793, years: "41", eval: "bad",
    note: "Israel's high-water mark of territory and wealth — the prosperous, hollow generation Amos and Hosea preached against.",
    refs: [["2 Kings 14:23–29", "2Kgs.14.23"]] },
  { name: "Zechariah", kingdom: "israel", start: 753, end: 752, years: "6 months", eval: "bad",
    note: "Killed by Shallum after six months — the fourth and last generation of Jehu's house, as promised.",
    refs: [["2 Kings 15:8–12", "2Kgs.15.8"]] },
  { name: "Shallum", kingdom: "israel", start: 752, end: 752, years: "1 month", eval: "bad",
    note: "Reigned one month; killed by Menahem.",
    refs: [["2 Kings 15:13–15", "2Kgs.15.13"]] },
  { name: "Menahem", kingdom: "israel", start: 752, end: 742, years: "10", eval: "bad",
    note: "Sacked Tiphsah with atrocities; paid Assyria a thousand talents to prop up his throne.",
    refs: [["2 Kings 15:14–22", "2Kgs.15.14"]] },
  { name: "Pekahiah", kingdom: "israel", start: 742, end: 740, years: "2", eval: "bad",
    note: "Killed in his own citadel by his captain Pekah.",
    refs: [["2 Kings 15:23–26", "2Kgs.15.23"]] },
  { name: "Pekah", kingdom: "israel", start: 740, end: 732, years: "20", eval: "bad",
    note: "Joined Syria against Judah (the crisis of Isaiah 7); Tiglath-pileser stripped Galilee and Gilead. Killed by Hoshea.",
    refs: [["2 Kings 15:27–31", "2Kgs.15.27"], ["2 Chronicles 28:5–8", "2Chr.28.5"]] },
  { name: "Hoshea", kingdom: "israel", start: 732, end: 722, years: "9", eval: "bad",
    note: "Israel's last king. His intrigue with Egypt brought Assyria down on Samaria — the city fell in 722 and the northern tribes went into exile.",
    refs: [["2 Kings 17", "2Kgs.17.1"]] },
];

const PROPHETS = [
  { name: "Elijah", kingdom: "israel", start: 870, end: 845,
    note: "Fire on Carmel against the prophets of Baal; taken up in the whirlwind.",
    refs: [["1 Kings 17–19; 21; 2 Kings 1–2", "1Kgs.17.1"]] },
  { name: "Elisha", kingdom: "israel", start: 848, end: 797,
    note: "Inherited Elijah's mantle and a double portion; his ministry spans six northern kings.",
    refs: [["2 Kings 2–9; 13:14–21", "2Kgs.2.1"]] },
  { name: "Jonah", kingdom: "israel", start: 785, end: 775, book: "Jonah",
    note: "Sent from Israel to Nineveh, Assyria's own capital — and furious that God relented.",
    refs: [["Jonah 1–4", "Jonah.1.1"], ["2 Kings 14:25", "2Kgs.14.25"]] },
  { name: "Amos", kingdom: "israel", start: 760, end: 750, book: "Amos",
    note: "A Judean shepherd sent north into Jeroboam II's prosperity: “let justice roll down like waters.”",
    refs: [["Amos 1–9", "Amos.1.1"]] },
  { name: "Hosea", kingdom: "israel", start: 755, end: 715, book: "Hosea",
    note: "His broken marriage acted out Israel's unfaithfulness through the kingdom's last thirty years.",
    refs: [["Hosea 1–14", "Hos.1.1"]] },

  { name: "Joel", kingdom: "judah", start: 835, end: 820, book: "Joel", uncertain: true,
    note: "Date much debated — placed here on the early view; some put him after the exile. “The day of the LORD” and the promise of the poured-out Spirit.",
    refs: [["Joel 1–3", "Joel.1.1"]] },
  { name: "Isaiah", kingdom: "judah", start: 740, end: 681, book: "Isaiah",
    note: "Called in the year Uzziah died; counselor to Ahaz and Hezekiah through the Assyrian crisis, and prophet of the suffering servant.",
    refs: [["Isaiah 1–66", "Isa.1.1"], ["2 Kings 19–20", "2Kgs.19.1"]] },
  { name: "Micah", kingdom: "judah", start: 740, end: 700, book: "Micah",
    note: "Isaiah's country contemporary: Bethlehem's coming ruler, and “what does the LORD require of you?”",
    refs: [["Micah 1–7", "Mic.1.1"]] },
  { name: "Nahum", kingdom: "judah", start: 660, end: 650, book: "Nahum",
    note: "Nineveh repented at Jonah's preaching; a century later Nahum announces its doom.",
    refs: [["Nahum 1–3", "Nah.1.1"]] },
  { name: "Zephaniah", kingdom: "judah", start: 640, end: 630, book: "Zephaniah",
    note: "Royal blood (Hezekiah's line) preaching judgment in Josiah's early years.",
    refs: [["Zephaniah 1–3", "Zeph.1.1"]] },
  { name: "Habakkuk", kingdom: "judah", start: 640, end: 609, book: "Habakkuk",
    note: "Asked why God tolerates evil, then how He can use Babylon to punish it. “The righteous shall live by his faith.”",
    refs: [["Habakkuk 1–3", "Hab.1.1"]] },
  { name: "Huldah", kingdom: "judah", start: 622, end: 622,
    note: "The prophetess who authenticated the newly found book of the law for Josiah.",
    refs: [["2 Kings 22:14–20", "2Kgs.22.14"]] },
  { name: "Jeremiah", kingdom: "judah", start: 627, end: 586, book: "Jeremiah · Lamentations",
    note: "Forty years pleading with Judah's last five kings; imprisoned, thrown in a cistern, vindicated by the fall he wept over.",
    refs: [["Jeremiah 1–52", "Jer.1.1"], ["Lamentations 1–5", "Lam.1.1"]] },
  { name: "Obadiah", kingdom: "judah", start: 586, end: 586, book: "Obadiah", uncertain: true,
    note: "Against Edom for gloating over Jerusalem's fall — most likely just after 586.",
    refs: [["Obadiah", "Obad.1.1"]] },

  { name: "Daniel", kingdom: "exile", start: 605, end: 560, book: "Daniel",
    note: "Taken in the first deportation; served Babylon's court through the exile and beyond (to ~536).",
    refs: [["Daniel 1–12", "Dan.1.1"]] },
  { name: "Ezekiel", kingdom: "exile", start: 593, end: 571, book: "Ezekiel",
    note: "Priest exiled with Jehoiachin in 597; saw the glory leave the temple — and return to a new one.",
    refs: [["Ezekiel 1–48", "Ezek.1.1"]] },
];

const WRITINGS = [
  { name: "Psalms of David", year: 1000,
    note: "Many psalms come from David's reign (c. 1010–971); the Psalter kept growing to the exile and after.",
    refs: [["Psalm 3", "Ps.3.1"], ["Psalm 51", "Ps.51.1"]] },
  { name: "Proverbs · Song · Ecclesiastes", year: 950,
    note: "The wisdom books associated with Solomon's court (Proverbs also credits Agur and Lemuel; Ecclesiastes' date is debated).",
    refs: [["Proverbs 1", "Prov.1.1"], ["Song of Solomon 1", "Song.1.1"], ["Ecclesiastes 1", "Eccl.1.1"]] },
];

/* The running text: which chapters narrate each stretch of the period.
   Rail 0 = Samuel–Kings, rail 1 = Chronicles. Dates follow the reign dates
   above; blocks are cut at natural seams in the narrative. */
const CHAPTERS = [
  { name: "1 Samuel 1–8", short: "1 Sam 1–8", rail: 0, start: 1060, end: 1050, osis: "1Sam.1.1",
    note: "Samuel's birth, call, and judgeship — and Israel's demand for a king. (The story begins c. 1100; the chart opens here.)" },
  { name: "1 Samuel 9–31", short: "1 Sam 9–31", rail: 0, start: 1050, end: 1010, osis: "1Sam.9.1",
    note: "Saul anointed and rejected; David anointed, hunted through the wilderness, sparing his king twice." },
  { name: "2 Samuel 1–24", short: "2 Sam 1–24", rail: 0, start: 1010, end: 971, osis: "2Sam.1.1",
    note: "David's reign: the covenant promise of an everlasting house — then Bathsheba, and Absalom." },
  { name: "1 Kings 1–11", short: "1 Kgs 1–11", rail: 0, start: 971, end: 931, osis: "1Kgs.1.1",
    note: "Solomon: the temple built and filled, wisdom the world came to hear, a heart turned by many wives." },
  { name: "1 Kings 12–16", short: "1 Kgs 12–16", rail: 0, start: 931, end: 874, osis: "1Kgs.12.1",
    note: "The kingdom splits at Shechem; Jeroboam's golden calves; northern dynasties rise and murder each other." },
  { name: "1 Kings 17–22", short: "1 Kgs 17–22", rail: 0, start: 874, end: 853, osis: "1Kgs.17.1",
    note: "Elijah against Ahab: fire on Carmel, Naboth's vineyard, the arrow at Ramoth-gilead." },
  { name: "2 Kings 1–8", short: "2 Kgs 1–8", rail: 0, start: 853, end: 841, osis: "2Kgs.1.1",
    note: "The whirlwind takes Elijah; Elisha's ministry — healed water, fed hundreds, Naaman washed clean." },
  { name: "2 Kings 9–13", short: "2 Kgs 9–13", rail: 0, start: 841, end: 796, osis: "2Kgs.9.1",
    note: "Jehu's furious purge of Ahab's house; Athaliah's coup in Judah and the boy-king Joash hidden in the temple." },
  { name: "2 Kings 14–17", short: "2 Kgs 14–17", rail: 0, start: 796, end: 722, osis: "2Kgs.14.1",
    note: "The long slide north — six kings fall to conspiracy — until Assyria takes Samaria and Israel is scattered." },
  { name: "2 Kings 18–20", short: "2 Kgs 18–20", rail: 0, start: 722, end: 687, osis: "2Kgs.18.1",
    note: "Hezekiah trusts the LORD against Sennacherib; the angel strikes the camp; fifteen years added to a life." },
  { name: "2 Kings 21–23", short: "2 Kgs 21–23", rail: 0, start: 687, end: 609, osis: "2Kgs.21.1",
    note: "Manasseh's half-century of darkness; the Book of the Law found in the rubble and Josiah's reform." },
  { name: "2 Kings 24–25", short: "2 Kgs 24–25", rail: 0, start: 609, end: 560, osis: "2Kgs.24.1",
    note: "Three deportations; the temple burned. The book ends with David's heir lifted from a Babylonian prison." },

  { name: "1 Chronicles 10–29", short: "1 Chr 10–29", rail: 1, start: 1010, end: 971, osis: "1Chr.10.1",
    note: "Saul's end in a single chapter, then David seen from the temple's side: the ark brought up, the plans drawn, Solomon charged." },
  { name: "2 Chronicles 1–9", short: "2 Chr 1–9", rail: 1, start: 971, end: 931, osis: "2Chr.1.1",
    note: "Solomon's temple: built, dedicated, filled with the glory of the LORD." },
  { name: "2 Chronicles 10–16", short: "2 Chr 10–16", rail: 1, start: 931, end: 871, osis: "2Chr.10.1",
    note: "Judah's story told alone: Rehoboam to Asa — the Chronicler passes over the northern kings entirely." },
  { name: "2 Chronicles 17–20", short: "2 Chr 17–20", rail: 1, start: 871, end: 849, osis: "2Chr.17.1",
    note: "Jehoshaphat sends teachers of the law through the cities of Judah; a choir leads the army to war." },
  { name: "2 Chronicles 21–28", short: "2 Chr 21–28", rail: 1, start: 849, end: 715, osis: "2Chr.21.1",
    note: "From Jehoram's fratricide to Ahaz nailing the temple doors shut — with Joash, Uzziah, and Jotham between." },
  { name: "2 Chronicles 29–32", short: "2 Chr 29–32", rail: 1, start: 715, end: 687, osis: "2Chr.29.1",
    note: "Hezekiah reopens the doors in his first month and keeps a Passover Israel had not seen since Solomon." },
  { name: "2 Chronicles 33–36", short: "2 Chr 33–36", rail: 1, start: 687, end: 555, osis: "2Chr.33.1",
    note: "Manasseh repents in Babylonian chains; Josiah's Passover; the fall — and the book's last word is Cyrus's decree to go home." },
];

const EVENTS = [
  { year: 931, label: "The kingdom divides", note: "Rehoboam's harsh answer at Shechem; ten tribes follow Jeroboam." },
  { year: 722, label: "Samaria falls to Assyria", note: "The northern kingdom ends; Israel deported (2 Kings 17)." },
  { year: 701, label: "Sennacherib besieges Jerusalem", note: "Assyria takes 46 cities of Judah but not Jerusalem (2 Kings 18–19)." },
  { year: 605, label: "First deportation", note: "Nebuchadnezzar takes captives including Daniel (Daniel 1)." },
  { year: 597, label: "Second deportation", note: "Jehoiachin, Ezekiel, and ten thousand exiled (2 Kings 24)." },
  { year: 586, label: "Jerusalem falls to Babylon", note: "City and temple burned; the southern kingdom ends (2 Kings 25)." },
  { year: 562, label: "Jehoiachin released", note: "Babylon's new king lifts David's heir from prison — 2 Kings ends on this hope." },
];
